config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'events#index'

  resources :events, only: [:index, :show]
  resources :event_categories, only: [:show]
  resource :cart, only: [:show] do
    put 'add/:event_id', to: 'carts#add', as: :add_to
    put 'remove/:event_id', to: 'carts#remove', as: :remove_from
    put 'remove_one/:event_id', to: 'carts#removeone', as: :remove_one
  end
  resource :charges, only: [:new, :create]
  resource :order, only: [:show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :alternate_image, AlternateImageUploader

  belongs_to :event_category
  has_many :orders
  has_many :users, through: :orders
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  has_many :events
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :events, through: :orders

  def current_user_cart
    "cart#{id}"
  end

  def cart_expire_time
    $redis.expire(current_user_cart, 1800)
  end

  def add_to_cart(event_id)
    $redis.hincrby current_user_cart, event_id, 1
    cart_expire_time
  end

  def remove_from_cart(event_id)
    $redis.hdel current_user_cart, event_id
  end

  def remove_one_from_cart(event_id)
    $redis.hincrby current_user_cart, event_id, -1
  end

  def cart_count
    quantities = $redis.hvals "cart#{id}"
    quantities.reduce(0) { |sum, qty| sum + qty.to_i }
  end

  def cart_total_price
    get_cart_events_with_qty.map { |event, qty| event.price * qty.to_i }.reduce(:+)
  end

  def get_cart_events_with_qty
    cart_ids = []
    cart_qtys = []
    ($redis.hgetall current_user_cart).map do |key, value|
      cart_ids << key
      cart_qtys << value
    end
    cart_events = Event.find(cart_ids)
    cart_events.zip(cart_qtys)
  end

  def purchase_cart_events!
    $redis.del current_user_cart
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

 def show
   @cart_events_with_qty = current_user.get_cart_events_with_qty
   @cart_total = 0
   @cart_events_with_qty.empty? ? @cart_total : @cart_total = current_user.cart_total_price
 end

 def add
   current_user.add_to_cart(params[:event_id])
   redirect_to cart_path
 end

 def remove
   current_user.remove_from_cart(params[:event_id])
   redirect_to cart_path
 end

 def removeone
   current_user.remove_one_from_cart(params[:event_id])
   redirect_to cart_path
 end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    Stripe.api_key = Rails.configuration.stripe[:secret_key]

    Payments::PaymentService.new(charge_params, current_user).call
    OrderMailerWorker.perform_async(current_user.email)
    redirect_to order_path
  end

  private

  def charge_params
    params.permit(:stripeEmail, :stripeToken, :cart)
  end
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  def show
    @category = EventCategory.find(params[:id])
    @events = @category.events.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order('name').page(params[:page]).per(15)
  end

  def show
    @event = Event.find(params[:id])
    category_events_count = -> (c) { EventCategory.all.select{|event_category| event_category.events.count > 10} }
    @popular_categories = EventCategory.all.map(&category_events_count).uniq.flatten.map(&:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @cart = current_user.current_user_cart
    @order = current_user.get_cart_events_with_qty

    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@order, view_context)
        send_data pdf.render, filename: "order-#{current_user.email}-#{DateTime.now}",
                  type: 'application/pdf',
                  disposition: 'inline'
      end
      expire_paid_cart
    end
  end

  private

  def expire_paid_cart
    $redis.expire(@cart, 60)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/show.html.erb
<div class="container">
   <div class="card shopping-cart">
      <div class="card-header bg-dark text-light">
          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
          Shopping cart
          <%= link_to "Continue shopping", root_path, class: "btn btn-outline-info btn-sm pull-right" %>
          <div class="clearfix"></div>
      </div>
      <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
        <h4>My Cart</h4>
        <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> tickets!</p>
      </div>
      <div class="card-body">
        <!-- PRODUCT -->
        <div class="row">
          <%@cart_events_with_qty.each do |array|%>
            <%product = array[0]%>
            <%qty = array[1]%>
            <div class="col-12 col-sm-12 col-md-2 text-center">
                    <!-- <img class="img-responsive" src="ticket.jpg" alt="prewiew" width="120" height="80"> -->
                    <%= image_tag "ticket.jpg", class: "img-responsive", width: "120", height: "80"%>
            </div>
            <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                <h4 class="product-name"><strong><%=product.name%></strong></h4>
                <h6>
                    <small><%=product.description.truncate(200, omission: '... (continued)')%></small>
                </h6>
            </div>
            <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
              <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                  <h6><strong><%=product.price%><span class="text-muted">x</span></strong></h6>
              </div>
              <div class="col-4 col-sm-4 col-md-4">
                <div class="quantity">
                  <input type="button" value="+" class="plus">
                  <input type="number" step="1" max="2" min="1" value="<%=qty%>" title="Qty" class="qty"
                         size="4">

                    <% if qty.to_i >= 0 %>
                      <%=link_to add_to_cart_path(product), method: :put do %>
                        <input type="button" value="+" class="plus">
                      <% end %>
                    <% end %>

                    <% if qty.to_i >= 2 %>
                      <%=link_to remove_one_cart_path(product), method: :put do %>
                        <input type="button" value="-" class="minus">
                      <% end %>
                    <% end %>
                </div>
              </div>
              <div class="col-2 col-sm-2 col-md-2 text-right">
                  <%=link_to remove_from_cart_path(product), class: "btn btn-outline-danger btn-xs", method: :put do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <%end%>
              </div>
            </div>
          <% end %>
        </div>
        <hr>
        <!-- END PRODUCT -->
        </div>
        <div class="card-footer">
          <div class="pull-right" style="margin: 10px">
            <% if @cart_total > 0 %>
              <%= form_tag charges_path do %>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="What's happening Kampala"
                        data-amount=@cart_total
                        data-locale="auto"></script>
              <% end %>
            <% else %>
              <button type="button" class="btn btn-secondary" disabled>Add item to cart first</button>
            <% end %>
            <div class="pull-right" style="margin: 5px">
                Total price: <b><%=@cart_total%></b>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/events/index.html.erb
<div class="container">
    <h3 class="h3">Featured Events</h3>
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-md-3 col-sm-6">
            <div class="product-grid2">
                <div class="product-image2">
                    <%= link_to event_path(event) do %>
                      <%= image_tag(event.image.to_s, class: "pic-1", style: "height: 400px") %>
                      <%= image_tag(event.alternate_image.to_s, class: "pic-2", style: "height: 400px") %>
                    <% end %>
                    <ul class="social">
                        <li><a href="<%=event_path(event)%>" data-tip="View"><i class="fa fa-eye"></i></a></li>
                    </ul>
                    <%=link_to 'Add to Cart', add_to_cart_path(event), method: :put, class: "add-to-cart"%>
                </div>
                <div class="product-content">
                    <h3 class="title">
                      <%=link_to event_path(event) do %>
                        <%=event.name%>
                      <% end %>
                    </h3>
                    <span class="price">UGX <%=event.price%></span>
                </div>
            </div>
        </div>
      <% end %>
    </div>
</div>
<hr>

<%= paginate @events %>

app/views/events/show.html.erb
<div class="container">
    <h3 class="h3 event-show">Find out what's happening in Kampala</h3>
    <div class="row">
      <div class="col-md-4 col-sm-6">
        <div class="product-grid2">
            <div class="product-image2">
                <a href="#">
                  <%= image_tag(@event.image.to_s, class: "pic-1", style: "height: 400px") %>
                  <%= image_tag(@event.alternate_image.to_s, class: "pic-2", style: "height: 400px") %>
                </a>
                <%=link_to 'Add to Cart', add_to_cart_path(@event), method: :put, class: "add-to-cart"%>
            </div>
            <div class="product-content">
                <h3 class="title"><%=@event.name%></h3>
                <span class="price">UGX <%=@event.price%></span>
            </div>
        </div>
      </div>
      <div class="col-md-8 col-sm-6">
        <h3 class="event-show"><%=@event.name%></h3>
        <p class="event-show"><%=@event.description%></p>
      </div>
    </div>
</div>
<hr>

<h3 class="h3 event-show">Popular Categories</h3>
<%@popular_categories.each do |c|%>
  <p><%=c %><br></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="row">
  <%@order.each do |array|%>
    <%product = array[0]%>
    <%qty = array[1]%>
    <div class="col-12 col-sm-12 col-md-2 text-center">
      <%= image_tag "ticket.jpg", class: "img-responsive"%>
    </div>
    <div class="col-12">
      <h4 class="product-name"><strong><%=product.name%></strong></h4>
      <h6>
        <small><%=product.description.truncate(200, omission: '... (continued)')%></small>
      </h6>
    </div>
    <%end%>
  </div>
<%=link_to 'Printable Receipt (PDF)', order_path(@order, format: 'pdf') %><br>
<%=link_to 'Go To Home', root_path %>